name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          max_post_count: "4"
          feed_list: "https://medium.com/feed/@ajbrohi"
